"""Grouped, domain-stratified splits of the compression-trace corpus.

`dl-students/dolci-compression-traces` holds rollouts generated by Qwen3-0.6B from
`allenai/Dolci-Think-RL-7B` prompts. Every prompt appears **more than once** with a
different trace, which makes a row-level split unsafe: the training target is the
answer, so a prompt landing in both train and val leaks the exact eval target.

Deliberately a sibling of `dolci.py` rather than a modification of it. The SFT
campaigns depend on that module's exact split semantics and must not shift
underneath them.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np
from datasets import Dataset, DatasetDict, load_dataset
from omegaconf import DictConfig

from cot_compression.compression import compressed_messages
from cot_compression.data.answers import (
    cot_token_ids,
    extract_answer_trace,
    prefix_token_ids,
    tokenize_answer,
)
from cot_compression.data.chat import IGNORE_INDEX
from cot_compression.data.dolci import (
    load_dataset_dict,
    save_dataset_dict_atomic,
    tokenized_dir,
)

# Columns the split and the downstream encoder pipeline require. Validated on the
# raw dataset before anything else runs, so a schema drift fails by name rather
# than by a KeyError thousands of rows into a map().
REQUIRED_COLUMNS = (
    "prompt_id",
    "rollout_id",
    "rollout_index",
    "domain",
    "messages",
    "complete",
    "ended_by_eos",
    "truncated",
)

# Kept through to the prepared splits. `correct` and `extracted_answer` are carried
# so math results can be reported split by correctness (only `math` is graded);
# everything else in the 38-column source schema is provenance we do not consume.
KEPT_COLUMNS = (
    "prompt_id",
    "rollout_id",
    "rollout_index",
    "domain",
    "messages",
    "correct",
    "extracted_answer",
)

SPLITS = ("train", "val", "test")


@dataclass(frozen=True)
class TraceSplits:
    train: Dataset
    val: Dataset
    test: Dataset


@dataclass(frozen=True)
class FilterReport:
    """Per-criterion drop counts.

    `complete` is authoritative on its own -- the dataset card defines it as
    natural stop/EOS, a closed `</think>`, a non-empty visible response and no
    generation error. The other two are reported only to surface disagreement:
    measured on the v1 snapshot, 81 rows stop naturally yet are incomplete, so a
    conjunction would be strictly weaker than `complete` alone, not stronger.
    """

    total: int
    kept: int
    dropped_incomplete: int
    not_ended_by_eos: int
    truncated: int
    complete_disagrees_with_flags: int

    def format(self) -> str:
        return (
            f"trace filter: kept {self.kept}/{self.total} "
            f"({self.kept / max(self.total, 1):.1%}); "
            f"dropped {self.dropped_incomplete} on complete==False "
            f"[not_ended_by_eos={self.not_ended_by_eos}, truncated={self.truncated}, "
            f"complete!=(eos & ~truncated) on {self.complete_disagrees_with_flags} rows]"
        )


def validate_trace_schema(dataset: Dataset) -> None:
    missing = [name for name in REQUIRED_COLUMNS if name not in dataset.column_names]
    if missing:
        raise ValueError(
            f"Trace dataset is missing required columns {missing}. "
            f"Found: {sorted(dataset.column_names)}"
        )


def filter_complete(dataset: Dataset) -> tuple[Dataset, FilterReport]:
    """Keep only rollouts that finished naturally.

    Incomplete rows are unusable for an answer-likelihood objective rather than
    merely low quality: measured on the v1 snapshot, 100% of sampled incomplete
    rows have an empty `extracted_answer`, and 82% never closed `</think>` at all,
    so `extract_answer_trace` returns None and the loss is undefined. The 18% that
    did close it carry a truncated response, which as a target would train the
    encoder to preserve a non-conclusion.
    """
    complete = np.asarray(dataset["complete"], dtype=bool)
    ended = np.asarray(dataset["ended_by_eos"], dtype=bool)
    truncated = np.asarray(dataset["truncated"], dtype=bool)

    report = FilterReport(
        total=int(complete.size),
        kept=int(complete.sum()),
        dropped_incomplete=int((~complete).sum()),
        not_ended_by_eos=int((~ended).sum()),
        truncated=int(truncated.sum()),
        complete_disagrees_with_flags=int((complete != (ended & ~truncated)).sum()),
    )
    kept = dataset.select(np.flatnonzero(complete).tolist())
    return kept, report


def split_trace_groups(
    prompt_ids: np.ndarray,
    domains: np.ndarray,
    rollout_indices: np.ndarray,
    *,
    fractions: tuple[float, float, float],
    seed: int,
) -> dict[str, np.ndarray]:
    """Row indices per split: grouped by prompt, stratified by domain.

    Pure over arrays so the invariants that matter -- zero prompt overlap,
    preserved domain proportions, one trace per prompt in val/test -- are testable
    without materializing a dataset.

    Steps 2-7 of the documented pipeline (step 1, filtering, is the caller's):

    2. group rows by ``prompt_id``;
    3. assign each group its domain, verifying the group does not span two;
    4. stratify groups by domain and shuffle within each stratum;
    5. split *groups* 90/5/5 by floor boundaries, per stratum;
    6. expand groups back to rows and shuffle;
    7. reduce val and test to one trace per prompt.

    Step 7 is what makes the reported standard errors correct: `summarize_method`
    treats samples as independent, and two rollouts of one prompt are not.

    Returns arrays of indices into the input arrays, one per split.
    """
    n_rows = prompt_ids.size
    if not (domains.size == n_rows and rollout_indices.size == n_rows):
        raise ValueError(
            "prompt_ids, domains and rollout_indices must have equal length; got "
            f"{prompt_ids.size}, {domains.size}, {rollout_indices.size}."
        )
    if n_rows == 0:
        raise ValueError("Cannot split an empty set of rows.")
    if len(fractions) != 3 or abs(float(sum(fractions)) - 1.0) > 1e-9:
        raise ValueError(
            f"fractions must be three values summing to 1; got {fractions}."
        )
    if any(f <= 0.0 for f in fractions):
        raise ValueError(f"every split fraction must be positive; got {fractions}.")

    # Step 2. np.unique returns sorted uniques, so group ids are a deterministic
    # function of the prompt_id strings alone -- independent of row order.
    unique_prompts, group_of_row = np.unique(prompt_ids, return_inverse=True)
    n_groups = int(unique_prompts.size)

    # Step 3. Duplicate-index assignment is last-write-wins, which is why the
    # result is verified against every row rather than trusted.
    domain_values, domain_of_row = np.unique(domains, return_inverse=True)
    domain_of_group = np.full(n_groups, -1, dtype=np.int64)
    domain_of_group[group_of_row] = domain_of_row
    disagrees = domain_of_group[group_of_row] != domain_of_row
    if disagrees.any():
        offender = unique_prompts[group_of_row[np.flatnonzero(disagrees)[0]]]
        raise ValueError(
            f"prompt_id {offender!r} spans more than one domain. Domains are "
            "expected to be prompt-disjoint; if that no longer holds, the "
            "stratification key must change."
        )

    # Steps 4-5. One rng consumed in sorted domain order, so the assignment is
    # reproducible regardless of how the strata happen to be enumerated.
    rng = np.random.default_rng(seed)
    groups_per_split: dict[str, list[np.ndarray]] = {name: [] for name in SPLITS}
    for code, domain_name in enumerate(domain_values):
        groups = np.flatnonzero(domain_of_group == code)
        groups = groups[rng.permutation(groups.size)]
        size = int(groups.size)
        n_train = int(np.floor(fractions[0] * size))
        n_val = int(np.floor((fractions[0] + fractions[1]) * size)) - n_train
        n_test = size - n_train - n_val
        if min(n_train, n_val, n_test) == 0:
            raise ValueError(
                f"Domain {domain_name!r} has only {size} prompt groups, too few to "
                f"split {fractions} without an empty slice "
                f"(train={n_train}, val={n_val}, test={n_test})."
            )
        groups_per_split["train"].append(groups[:n_train])
        groups_per_split["val"].append(groups[n_train : n_train + n_val])
        groups_per_split["test"].append(groups[n_train + n_val :])

    def rows_of(groups: np.ndarray) -> np.ndarray:
        """Expand group ids to row indices without a per-group Python loop."""
        member = np.zeros(n_groups, dtype=bool)
        member[groups] = True
        return np.flatnonzero(member[group_of_row])

    def one_row_per_group(rows: np.ndarray) -> np.ndarray:
        """Lowest rollout_index per prompt; ties broken by row index.

        Deterministic and independent of the shuffles above, so val/test contents
        do not move when the seed changes only the ordering.
        """
        order = np.lexsort((rows, rollout_indices[rows], group_of_row[rows]))
        ordered = rows[order]
        groups = group_of_row[ordered]
        first = np.ones(groups.size, dtype=bool)
        first[1:] = groups[1:] != groups[:-1]
        return ordered[first]

    out: dict[str, np.ndarray] = {}
    for name in SPLITS:
        rows = rows_of(np.concatenate(groups_per_split[name]))
        # Step 7 before the shuffle: selection must not depend on row order.
        if name != "train":
            rows = one_row_per_group(rows)
        # Step 6. Interleave domains -- the batcher length-sorts within a
        # length_group_size window, and domain-blocked rows would make those
        # windows domain-homogeneous.
        out[name] = rows[rng.permutation(rows.size)]
    return out


def describe_splits(
    indices: dict[str, np.ndarray],
    prompt_ids: np.ndarray,
    domains: np.ndarray,
) -> str:
    """Realized split sizes and per-domain proportions, for the build log.

    **Prompt share is the number the configured fractions govern**, and it lands
    on them exactly (to within one prompt per stratum, from the floor boundaries).
    Row share does not, and is expected to look lopsided: step 7 keeps a single
    trace per prompt in val and test while train keeps all of them, so a 90/5/5
    prompt split reads as roughly 95/2.5/2.5 by row. Both are printed so the
    difference is visible rather than alarming.
    """
    total_rows = sum(int(rows.size) for rows in indices.values())
    total_prompts = sum(
        int(np.unique(prompt_ids[rows]).size) for rows in indices.values()
    )
    lines = [f"split sizes (rows={total_rows}, prompts={total_prompts}):"]
    for name in SPLITS:
        rows = indices[name]
        prompts = int(np.unique(prompt_ids[rows]).size)
        lines.append(
            f"  {name:5s} prompts={prompts:>7} ({prompts / max(total_prompts, 1):6.2%})"
            f"   rows={rows.size:>7} ({rows.size / max(total_rows, 1):6.2%})"
        )
    lines.append("per-domain prompt share:")
    all_domains = np.unique(domains)
    for domain in all_domains:
        parts = []
        for name in SPLITS:
            rows = indices[name]
            in_domain = domains[rows] == domain
            prompts = np.unique(prompt_ids[rows][in_domain]).size
            denom = np.unique(prompt_ids[rows]).size
            parts.append(f"{name}={prompts / max(denom, 1):6.2%}")
        overall = np.unique(prompt_ids[domains == domain]).size
        parts.append(f"n_prompts={overall}")
        lines.append(f"  {str(domain):22s} " + "  ".join(parts))
    return "\n".join(lines)


def assert_no_prompt_overlap(
    indices: dict[str, np.ndarray], prompt_ids: np.ndarray
) -> None:
    """No prompt may appear in two splits.

    Checked on every build, not once: the training target is the answer, so a
    shared prompt leaks the exact quantity the eval measures.
    """
    sets = {name: set(prompt_ids[rows].tolist()) for name, rows in indices.items()}
    for left in SPLITS:
        for right in SPLITS:
            if left >= right:
                continue
            shared = sets[left] & sets[right]
            if shared:
                raise ValueError(
                    f"{len(shared)} prompt_ids appear in both {left} and {right} "
                    f"(e.g. {sorted(shared)[:3]}). The split is contaminated."
                )


def prepared_dir(cfg: DictConfig) -> Path:
    return Path(str(cfg.data.prepared_dir))


def build_trace_data(cfg: DictConfig) -> Path:
    """Materialize the three splits to disk, or return the existing ones.

    Filtering precedes grouping because it changes the group structure: a prompt
    can lose every rollout, and completion rates range from 73.5% (`code_stdio`)
    to 99.4% (`general_quality`), so stratifying on the unfiltered distribution
    would stratify on the wrong one.
    """
    out = prepared_dir(cfg)
    if out.exists():
        return out

    raw = load_dataset(
        str(cfg.data.source_name),
        name=cfg.data.get("source_config"),
        split=str(cfg.data.source_split),
    )
    if not isinstance(raw, Dataset):
        raise ValueError(f"Expected a single Dataset from {cfg.data.source_name}.")
    validate_trace_schema(raw)

    # Step 1: canonical order, then filter. Sorting first makes every downstream
    # shuffle a function of the data alone -- parquet read order is stable in
    # practice but is not a guarantee across `datasets` versions.
    raw = raw.sort("rollout_id")
    kept, report = filter_complete(raw)
    print(report.format(), flush=True)

    prompt_ids = np.asarray(kept["prompt_id"], dtype=object)
    domains = np.asarray(kept["domain"], dtype=object)
    rollout_indices = np.asarray(kept["rollout_index"], dtype=np.int64)

    indices = split_trace_groups(
        prompt_ids,
        domains,
        rollout_indices,
        fractions=(
            float(cfg.data.train_fraction),
            float(cfg.data.val_fraction),
            float(cfg.data.test_fraction),
        ),
        seed=int(cfg.data.seed),
    )
    assert_no_prompt_overlap(indices, prompt_ids)
    print(describe_splits(indices, prompt_ids, domains), flush=True)

    drop = [c for c in kept.column_names if c not in KEPT_COLUMNS]
    splits = DatasetDict(
        {
            name: kept.select(indices[name].tolist()).remove_columns(drop)
            for name in SPLITS
        }
    )

    return save_dataset_dict_atomic(splits, out)


def _measure_row(example: dict[str, Any], tokenizer: Any) -> dict[str, Any]:
    """Token counts for one rollout, without keeping the token ids.

    Deliberately stores counts, not ids. `plan_epoch` needs every length *before*
    training starts -- that is what makes length-bucketed batching and an exact
    step count possible -- but the ids themselves are cheap to recompute in a
    DataLoader worker and would cost ~10 GB of scratch to cache. Tokenizing
    ~1.2 B tokens per epoch across `num_workers` processes is a rounding error
    against a multi-hour epoch.

    `answer_length` is measured on the K=0 render and is **independent of K**
    (verified: the answer text and its tokenization do not change with the number
    of placeholders), so one measurement serves every compression ratio.
    """
    trace = extract_answer_trace(example["messages"])
    empty = {"prompt_length": 0, "cot_length": 0, "answer_length": 0}
    if trace is None:
        return empty
    try:
        cot_length = len(cot_token_ids(trace, tokenizer))
    except ValueError:
        return empty
    tokenized = tokenize_answer(
        tokenizer=tokenizer,
        messages=compressed_messages(trace, 0),
        answer=trace.answer,
        max_length=None,
    )
    if tokenized is None:
        return empty
    return {
        "prompt_length": len(prefix_token_ids(trace, tokenizer)),
        "cot_length": cot_length,
        "answer_length": sum(1 for x in tokenized.labels if x != IGNORE_INDEX),
    }


def build_trace_lengths(cfg: DictConfig) -> Path:
    """Add per-row token counts to the splits, keyed by dataset *and* model.

    A second stage rather than columns on the splits themselves: the split is
    tokenizer-independent, and folding the two together would rebuild a multi-GB
    corpus every time the model changes. Mirrors `dolci.build_tokenized_sft_data`.

    Rows that cannot be measured -- no extractable answer, an empty CoT, or a
    render that defeats the answer-span search -- get zero lengths and are dropped
    here, so training never has to skip a row it has already batched.
    """
    from transformers import AutoTokenizer

    out = tokenized_dir(cfg)
    if out.exists():
        return out

    tokenizer = AutoTokenizer.from_pretrained(
        str(cfg.method.model_name),
        use_fast=bool(cfg.method.use_fast_tokenizer),
        trust_remote_code=bool(cfg.method.trust_remote_code),
    )
    splits = load_trace_data(cfg)
    source = DatasetDict(
        {"train": splits.train, "val": splits.val, "test": splits.test}
    )
    measured = source.map(
        _measure_row,
        fn_kwargs={"tokenizer": tokenizer},
        num_proc=int(cfg.data.tokenize_num_proc),
        desc="Measuring trace lengths",
    ).filter(
        lambda example: example["cot_length"] > 0 and example["answer_length"] > 0,
        num_proc=int(cfg.data.tokenize_num_proc),
        desc="Dropping rows with no usable trace or answer",
    )
    for name in SPLITS:
        dropped = len(source[name]) - len(measured[name])
        print(f"  {name:5s} measured {len(measured[name])} rows, dropped {dropped}")
    return save_dataset_dict_atomic(measured, out)


def load_trace_lengths(cfg: DictConfig) -> DatasetDict:
    out = tokenized_dir(cfg)
    if not out.exists():
        raise FileNotFoundError(
            f"No measured trace cache at {out}. Build it once with:\n"
            f"  uv run python scripts/run.py traces data={cfg.data.name}"
        )
    return load_dataset_dict(out)


def prepare_trace_data(cfg: DictConfig) -> Path:
    """Split, then measure. One operational step, one entry point."""
    build_trace_data(cfg)
    return build_trace_lengths(cfg)


def load_trace_data(cfg: DictConfig) -> TraceSplits:
    out = prepared_dir(cfg)
    if not out.exists():
        raise FileNotFoundError(
            f"No prepared trace splits at {out}. Build them once with:\n"
            f"  uv run python scripts/run.py traces data={cfg.data.name}"
        )
    loaded = load_dataset_dict(out)
    missing = [name for name in SPLITS if name not in loaded]
    if missing:
        raise ValueError(f"Prepared trace splits are missing {missing} at {out}.")
    return TraceSplits(train=loaded["train"], val=loaded["val"], test=loaded["test"])
