defaults:
  - paths: default
  - data: tiny_shakespeare_char
  - method: char_gpt/tiny
  - training: default
  - optim: adamw
  - logging: wandb
  - _self_

mode: train

hydra:
  run:
    dir: ${paths.output_dir}/runs/${data.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: true
